apiVersion: v1
kind: Namespace
metadata:
  name: vin-minecraft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraftpvc
  namespace: vin-minecraft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-rwx-ephemeral
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: vin-minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          imagePullPolicy: Always
          stdin: true
          tty: true
          resources:
            requests:
              cpu: "4"
              memory: "12Gi"
            limits:
              cpu: "12"
              memory: "24Gi"
          ports:
            - containerPort: 25565
              protocol: TCP
          env:
            - name: EULA
              value: "TRUE"
            - name: INIT_MEMORY
              value: "12G"
            - name: MAX_MEMORY
              value: "20G"
            - name: JVM_XX_OPTS
              value: "-XX:ParallelGCThreads=10 -XX:ConcGCThreads=5"
            - name: USE_AIKAR_FLAGS
              value: "true"
          volumeMounts:
            - mountPath: /data
              name: minecraftpvc
      volumes:
        - name: minecraftpvc
          persistentVolumeClaim:
            claimName: minecraftpvc
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: vin-minecraft
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mc.jacobbanghart.com
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: minecraft
