apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloudpv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: truenas.home
    path: /mnt/BasicPool/kubernetes/nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloudpvc
  namespace: nextcloud
spec:
  resources:
    requests:
      storage: 200Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nextcloudpv
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: 7.0.2
      sourceRef:
        kind: HelmRepository
        name: nextcloud
      interval: 5m
  values:
    persistence:
      enabled: true
      existingClaim: nextcloudpvc
      accessMode: ReadWriteMany
      size: 200Gi
      nextcloudData:
        enabled: true
        existingClaim: nextcloudpvc
        accessMode: ReadWriteMany
        size: 200Gi
    nextcloud:
      host: nextcloud.jacobbanghart.com
    internalDatabase:
      enabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: nextcloud
  annotations:
spec:
  rules:
    - host: nextcloud.jacobbanghart.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nextcloud
                port:
                  name: http
