apiVersion: v1
kind: Namespace
metadata:
  name: kasm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kasm
  namespace: kasm
spec:
  interval: 1m
  url: https://github.com/kasmtech/kasm-helm
  ref:
    branch: release/1.16.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: kasm
  namespace: kasm
spec:
  interval: 5m
  chart: kasm-single-zone
  sourceRef:
    name: kasm
    kind: GitRepository
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kasm
  namespace: kasm
spec:
  interval: 5m
  chartRef:
    kind: HelmChart
    name: kasm
    namespace: kasm
  values:
    global:
      namespace: kasm
      hostname: kasm.jacobbanghart.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasm-agent
  namespace: kasm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kasm-agent
  template:
    metadata:
      labels:
        app: kasm-agent
    spec:
      containers:
        - name: agent
          image: kasmweb/agent:1.16.0
          env:
            - name: SERVER_HOSTNAME
              value: "10.1.0.34"
            - name: SERVER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: MANAGER_HOSTNAME
              value: "kasm-agent-gateway"
            - name: MANAGER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kasm-secrets
                  key: manager-token
          ports:
            - containerPort: 4432
            - containerPort: 4444
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
---
apiVersion: v1
kind: Service
metadata:
  name: kasm-agent-gateway
  namespace: kasm
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app.kubernetes.io/name: kasm-proxy
