apiVersion: v1
kind: Namespace
metadata:
  name: kasm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kasm
  namespace: kasm
spec:
  interval: 1m
  url: https://github.com/kasmtech/kasm-helm
  ref:
    branch: release/1.16.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: kasm
  namespace: kasm
spec:
  interval: 5m
  chart: kasm-single-zone
  sourceRef:
    name: kasm
    kind: GitRepository
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kasm
  namespace: kasm
spec:
  interval: 5m
  chartRef:
    kind: HelmChart
    name: kasm
    namespace: kasm
  values:
    global:
      namespace: kasm
      hostname: kasm.jacobbanghart.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kasm-manager-ingress
  namespace: kasm
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - kasm.jacobbanghart.com
      secretName: kasm-ingress-cert
  rules:
    - host: kasm.jacobbanghart.com
      http:
        paths:
          - path: /manager_api/
            pathType: Prefix
            backend:
              service:
                name: kasm-manager
                port:
                  number: 8181
