apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns-repo
  namespace: external-dns
spec:
  interval: 5m0s
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-release
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: "1.15.2"
      sourceRef:
        kind: HelmRepository
        name: external-dns-repo
        namespace: external-dns
      interval: 10m
  values:
    provider:
      name: cloudflare
    sources:
      - ingress
      - service
    domainFilters:
      - jacobbanghart.com
    policy: sync
    txtOwnerId: external-dns
    extraArgs:
      - --cloudflare-dns-records-per-page=5000
    env:
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: cloudflare-credentials
            key: apiKey
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: cloudflare-credentials
            key: email
