apiVersion: v1
kind: Namespace
metadata:
  name: moxfielddecktoartists
---
apiVersion: v1
kind: Service
metadata:
  name: moxfielddecktoartists
  namespace: moxfielddecktoartists
spec:
  type: ClusterIP
  selector:
    app: moxfielddecktoartists
  ports:
    - port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moxfielddecktoartists
  namespace: moxfielddecktoartists
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moxfielddecktoartists
  template:
    metadata:
      labels:
        app: moxfielddecktoartists
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: moxfielddecktoartists
          image: ghcr.io/jacobbanghart/moxfielddecktoartists:v1.0.3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              memory: "500Mi"
              cpu: "1000m"
          ports:
            - containerPort: 4000
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moxfielddecktoartists
  namespace: moxfielddecktoartists
  labels:
    name: moxfielddecktoartists
spec:
  rules:
    - host: decktoartists.jacobbanghart.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: moxfielddecktoartists
                port:
                  number: 4000
