---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: portfolio
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: master
  url: ssh://git@gitlab.com/jacobmbanghart/astro-portfolio
  secretRef:
    name: flux-ssh-key