apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: portfolio
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@gitlab.com/jacobmbanghart/astro-portfolio
  secretRef:
    name: flux-ssh-key