apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 33.2.1
      sourceRef:
        kind: HelmRepository
        name: immich
      interval: 30m
  values:
    additionalArguments:
      # Configure your CertificateResolver here...
      #
      # HTTP Challenge
      # ---
      # Generic Example:
      #   - --certificatesresolvers.generic.acme.email=your-email@example.com
      #   - --certificatesresolvers.generic.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
      #   - --certificatesresolvers.generic.acme.httpChallenge.entryPoint=web
      #   - --certificatesresolvers.generic.acme.storage=/ssl-certs/acme-generic.json
      #
      # Prod / Staging Example:
      #   - --certificatesresolvers.staging.acme.email=your-email@example.com
      #   - --certificatesresolvers.staging.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      #   - --certificatesresolvers.staging.acme.httpChallenge.entryPoint=web
      #   - --certificatesresolvers.staging.acme.storage=/ssl-certs/acme-staging.json
      #   - --certificatesresolvers.production.acme.email=your-email@example.com
      #   - --certificatesresolvers.production.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
      #   - --certificatesresolvers.production.acme.httpChallenge.entryPoint=web
      #   - --certificatesresolvers.production.acme.storage=/ssl-certs/acme-production.json
      #
      # DNS Challenge
      # ---
      # Cloudflare Example:
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=jacobmbanghart@gmail.com
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
      - --certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme-cloudflare.json
    #
    # Generic (replace with your DNS provider):
    #  - --certificatesresolvers.generic.acme.dnschallenge.provider=generic
    #  - --certificatesresolvers.generic.acme.email=your-email@example.com
    #  - --certificatesresolvers.generic.acme.storage=/ssl-certs/acme-generic.json

    logs:
      # Configure log settings here...
      general:
        level: DEBUG

    ports:
      # Configure your entrypoints here...
      web:
        # (optional) Permanent Redirect to HTTPS
        redirectTo:
          port: websecure
      websecure:
        tls:
          enabled: true
          # (optional) Set a Default CertResolver
          certResolver: cloudflare

    env:
      # Set your environment variables here...
      #
      # DNS Challenge Credentials
      # ---
      # Cloudflare Example:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            key: email
            name: cloudflare-credentials
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            key: apiKey
            name: cloudflare-credentials

    # Persistent Storage
    persistence:
      enabled: true
      name: ssl-certs
      size: 1Gi
      path: /ssl-certs

    deployment:
      labels:
        release: prometheus
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"
      podLabels:
        release: prometheus
      initContainers:
        # The "volume-permissions" init container is required if you run into permission issues.
        # Related issue: https://github.com/containous/traefik/issues/6972
        - name: volume-permissions
          image: busybox:1.31.1
          command: ["sh", "-c", "chmod -Rv 600 /ssl-certs/* || echo oops"]
          volumeMounts:
            - name: ssl-certs
              mountPath: /ssl-certs

    ingressRoute:
      dashboard:
        enabled: true
        middlewares:
          - name: basic-auth

    # Set Traefik as your default Ingress Controller, according to Kubernetes 1.19+ changes.
    ingressClass:
      enabled: true
      isDefaultClass: true

    metrics:
      prometheus:
        addEntryPointsLabels: true
        addServicesLabels: true
        addRoutersLabels: true
    tracing:
      addInternals: false
      serviceName: traefik
      otlp:
        enabled: true
        grpc:
          enabled: true
          endpoint: signoz-otel-collector.signoz.svc.cluster.local:4317
          insecure: true

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: traefik
spec:
  basicAuth:
    secret: basic-auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resource
  namespace: traefik
  labels:
    name: traefik-dashboard
spec:
  rules:
    - host: traefik.jacobbanghart.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: traefik-dashboard
                port:
                  number: 8080
