apiVersion: v1
kind: Namespace
metadata:
  name: copyparty
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: copyparty
  name: srvcopypartyspv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: truenas.home
    path: /mnt/BasicPool/Filebrowser/srv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: copyparty
  name: srvcopypartyspvc
spec:
  resources:
    requests:
      storage: 200Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: srvcopypartyspv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: copyparty-cm
  namespace: copyparty
data:
  # https://github.com/9001/copyparty/blob/hovudstraum/docs/example.conf
  # https://www.youtube.com/watch?v=15_-hgsX2V0
  copyparty.conf: |
    # not actually YAML but lets pretend:
    # -*- mode: yaml -*-
    # vim: ft=yaml:


    [global]
      e2dsa  # enable file indexing and filesystem scanning
      e2ts   # enable multimedia indexing
      ansi   # enable colors in log messages
      z
      shr: /shr
      # q, lo: /cfg/log/%Y-%m%d.log   # log to file instead of docker

      # p: 3939          # listen on another port
      # ipa: 10.89.      # only allow connections from 10.89.*
      df: 16           # stop accepting uploads if less than 16 GB free disk space
      # ver              # show copyparty version in the controlpanel
      # grid             # show thumbnails/grid-view by default
      theme: 2         # monokai
      name: Jacobs Server  # change the server-name that's displayed in the browser
      stats, nos-dup   # enable the prometheus endpoint, but disable the dupes counter (too slow)
      no-robots, force-js  # make it harder for search engines to read your server


    [accounts]
      ed: wark  # username: password


    [/copyparty]
      /w/copyparty           # share /w/copyparty (the docker data volume)
      accs:
        rw: *      # everyone gets read-write access, but
        rwmda: ed  # the user "ed" gets read-write-move-delete-admin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copyparty
  namespace: copyparty
spec:
  selector:
    matchLabels:
      app: copyparty
  template:
    metadata:
      labels:
        app: copyparty
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: copyparty
          image: copyparty/ac:1.19.20
          env:
            - name: PRTY_UNSAFE_STATE
              value: "1"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 3923
          volumeMounts:
            - mountPath: /w
              name: srvpvc
            - mountPath: /cfg
              name: copyparty-cm
      volumes:
        - name: srvpvc
          persistentVolumeClaim:
            claimName: srvcopypartyspvc
        - name: copyparty-cm
          configMap:
            name: copyparty-cm
---
apiVersion: v1
kind: Service
metadata:
  name: copyparty
  namespace: copyparty
spec:
  selector:
    app: copyparty
  ports:
    - port: 3923
      targetPort: 3923
      name: copyparty
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: copyparty
  namespace: copyparty
  labels:
    name: copyparty
spec:
  rules:
    - host: copyparty.jacobbanghart.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: copyparty
                port:
                  number: 3923
