apiVersion: v1
kind: Namespace
metadata:
  name: immich
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immichpv
  namespace: immich
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: truenas.home
    path: /mnt/BasicPool/kubernetes/immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immichpvc
  namespace: immich
spec:
  resources:
    requests:
      storage: 200Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immichpv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-rwx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
  namespace: immich
spec:
  interval: 5m
  url: https://immich-app.github.io/immich-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami-postgres
  namespace: immich
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: "18.1.8"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: immich
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: v2.0.0
            envFrom:
              - secretRef:
                  name: immich-postgres-secret
            env:
              DB_HOSTNAME: immich-postgres
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-secret
                    key: POSTGRES_USER
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-secret
                    key: POSTGRES_PASSWORD
              DB_DATABASE:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-secret
                    key: POSTGRES_DB
    immich:
      persistence:
        library:
          existingClaim: immichpvc
      configuration: {}
    valkey:
      enabled: true
      persistence:
        data:
          storageClass: nfs-rwx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-postgres
  namespace: immich
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: bitnami-postgres
  values:
    global:
      postgresql:
        fullnameOverride: immich-postgres
        auth:
          existingSecret: immich-postgres-secret
          secretKeys:
            adminPasswordKey: POSTGRES_PASSWORD
            userPasswordKey: POSTGRES_PASSWORD
          username: immich
          database: immich
        usePasswordFiles: false
    primary:
      persistence:
        existingClaim: immich-postgres-pvc
      podSecurityContext: null
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ingress
  namespace: immich
spec:
  rules:
    - host: photos.jacobbanghart.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: immich-server
                port:
                  number: 2283
