apiVersion: v1
kind: Namespace
metadata:
  name: atm10-ryan
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atm10-ryan-pvc
  namespace: atm10-ryan
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-rwx-ephemeral
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atm10-ryan
  namespace: atm10-ryan
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: atm10-ryan
  template:
    metadata:
      labels:
        app: atm10-ryan
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java21
          imagePullPolicy: Always
          stdin: true
          tty: true
          resources:
            requests:
              cpu: "4"
              memory: "12Gi"
            limits:
              cpu: "12"
              memory: "32Gi"
          ports:
            - containerPort: 25565
              protocol: TCP
          env:
            - name: EULA
              value: "TRUE"
            - name: MODPACK_PLATFORM
              value: "AUTO_CURSEFORGE"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: curseforge-api-key
                  key: CF_API_KEY
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-10"
            - name: CF_FILENAME_MATCHER
              value: "6.6"
            - name: MODE
              value: "survival"
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: OPS
              value: "Jqwop"
            - name: INIT_MEMORY
              value: "12G"
            - name: MAX_MEMORY
              value: "16G"
            - name: JVM_XX_OPTS
              value: "-XX:ActiveProcessorCount=12 -XX:ParallelGCThreads=9 -XX:ConcGCThreads=3"
            - name: USE_AIKAR_FLAGS
              value: "true"
          volumeMounts:
            - mountPath: /data
              name: atm10-ryan-pvc
          startupProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 120
      volumes:
        - name: atm10-ryan-pvc
          persistentVolumeClaim:
            claimName: atm10-ryan-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: atm10-ryan
  namespace: atm10-ryan
  annotations:
    external-dns.alpha.kubernetes.io/hostname: atm10-ryan.jacobbanghart.com
spec:
  type: LoadBalancer
  selector:
    app: atm10-ryan
  ports:
    - port: 25566
      targetPort: 25565
      protocol: TCP
      name: minecraft
